CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    number VARCHAR(50) NOT NULL UNIQUE,
    numberb VARCHAR(50) NOT NULL UNIQUE,
    user VARCHAR(50)NOT NULL UNIQUE,
    pass VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);